<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class CarsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 18;

    public static function getMap(): array
    {
        $map = [
            'STRANA' => new ReferenceField(
                'STRANA', 
                CarStranaPropertyValuesTable::class, 
                ['=this.STRANA_ID' => 'ref.IBLOCK_ELEMENT_ID']
            ),

            'MANUFACTURER' => new ReferenceField(
                'MANUFACTURER', 
                CarManufacturerPropertyValuesTable::class, 
                ['=this.MANUFACTURER_ID' => 'ref.IBLOCK_ELEMENT_ID']
            )

        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
